First level 1
29th-WE-SOPT-Android-Part/Android-Songhyeon pull request #1
Opened 2021-10-10 12:59 UTC by ssonghyun101

필수과제만 했습돠! 도전과제는 나중에 올릴게요

2021-10-12 10:03 UTC, l2hyunwoo requested changes
수고했습니다

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/AndroidManifest.xml
> +        <activity android:name=".SignUpActivity"></activity>
```suggestion
        <activity android:name=".SignUpActivity" />
```

이렇게 적어도 좋을 듯

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/HomeActivity.kt
> +        Toast.makeText(this,"김송현님 환영합니다",Toast.LENGTH_SHORT).show()
```suggestion
        Toast.makeText(this, "김송현님 환영합니다", Toast.LENGTH_SHORT).show()
```

,와 글자 사이에는 간격을 두는게 코딩 컨벤션이긴 합니다. 올리시기 전에 Ctrl+Alt+L 누르면 파일 내 텍스트 정렬 가능

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +
이런 빈칸 없게 해주는 게 좋습니다.

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +        val signupintent = Intent(this, SignUpActivity::class.java)
두 단어로 구성된 변수는 camelCase로 적어주는게 좋습니다.
```suggestion
        val signupIntent = Intent(this, SignUpActivity::class.java)
```

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +        val intent = Intent(this, HomeActivity::class.java)
위에도 그렇고 인라인으로 아래와 같이 적어주셔도 될 것 같습니다. 그리고 이정도 양의 함수면 굳이 함수 분리까지 할 필요 없고 initButtonClickEvent에 몰아도 될 것 같습니다.

그리고 intent라고 하면 어떤 것이 떠오르시나요? 변수명을 보고 어떤 역할을 하는 변수인지 알아볼 수 있게 적어주면 좋을 것 같습니다 :)
```suggestion
        startActivity(Intent(this, HomeActivity::class.java))
```

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +        }
```suggestion
        with(binding) {
            btnLogin.setOnClickListener {
                val userId: String = etId.text.toString()
                val userPwd: String = etPwd.text.toString()
                if (userId.isEmpty() || userPwd.isEmpty()) {
                    Toast.makeText(this@SignInActivity, "로그인 실패", Toast.LENGTH_SHORT).show()
                } else {
                    moveHomeActivity()
                }
            }
        }
```

1. 일반적으로 apply 함수는 객체 자신을 다시 반환 하려는 경우에 사용합니다. 지금은 어떤 값을 반환받을 필요가 없기에 with를 사용하는 것이 조금 더 적절한 use case일 것 같습니다(동작은 같습니다만, 역할이 다릅니다)
2. pwd와 같은 축약어는 사용하지 않는 것이 가독성 증진에 기여합니다. userPwd보단 userPassword가 한눈에 더 이해가 쉽게 되지 않을까요?
3. etId.text.isEmpty()로만 해도 Edittext 내부의 text가 비었는 지 안 비었는 지 확인 가능합니다.
4. moveToHomeActivity()와 같은 경우 한 눈에 알아보기 쉽게 작명이 되어있습니다. 정말 좋네요

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/res/layout/activity_home.xml
> +        android:layout_width="wrap_content"
ratio 지정하려면 width나 height 중 하나는 0dp여야 되지 않나요?

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/textView"
textView와 같은 일반적인 아이디는 지양하면 좋을 것 같습니다!

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/res/layout/activity_signin.xml
> +    <androidx.appcompat.widget.AppCompatButton
Button이라고만 써도 안드로이드 theme에 의해 자동으로 AppCompatButton 혹은 MaterialButton과 매칭됩니다.

https://www.youtube.com/watch?v=QICJtfvsYc8

이거 한번 보시는걸 추천드려요

2021-10-12 10:03 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/res/values/strings.xml
> +    <string name="ksh">김송현</string>
ksh이 이 의미였구나....

2021-10-12 13:37 UTC, ssonghyun101 commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +        val signupintent = Intent(this, SignUpActivity::class.java)
엇 여기 왜 camelCase로 안되어있지 감쟈합니다

2021-10-12 13:37 UTC, ssonghyun101 commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +        val intent = Intent(this, HomeActivity::class.java)
아 걍 앱잼하면서 습관돼서ㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-12 13:38 UTC, ssonghyun101 commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +        }
오 안그래도 apply와 with 차이점 좀 공부하려고 했는데 감쟈합니다

2021-10-12 13:39 UTC, ssonghyun101 commented on 29th_first_semina/app/src/main/res/layout/activity_home.xml
> +        android:layout_width="wrap_content"
아.. 맞다

2021-10-12 13:39 UTC, ssonghyun101 commented on 29th_first_semina/app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/textView"
어 저기 왜 저렇게 되어있지2

2021-10-12 13:40 UTC, ssonghyun101 commented on 29th_first_semina/app/src/main/res/values/strings.xml
> +    <string name="ksh">김송현</string>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ\

2021-10-13 10:03 UTC, mdb1217 approved these changes

2021-10-19 16:02 UTC, mdb1217 commented
과제 수고했으~ 다음 과제도 파이팅~!!

2021-10-19 16:03 UTC, mdb1217 commented on 29th_first_semina/app/build.gradle
> +        minSdkVersion 28
minSdk 혹시 28로 하신 특별한 이유가 있을까요??

2021-10-19 16:04 UTC, mdb1217 commented on 29th_first_semina/app/build.gradle
> +            viewBinding = true
kts가 아닌 groovy에서의 올바른 표기법은
`viewBinding true` 이런 식입니다~!! :)

2021-10-19 16:06 UTC, mdb1217 commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +                val userPwd: String = etPwd.text.toString()
코틀린에서는 타입추론 기능을 지원하기 때문에
```suggestion
                val userId = etId.text.toString()
                val userPwd = etPwd.text.toString()
```
이런식으로 작성하셔도 괜찮습니다~!!

2021-10-19 16:07 UTC, mdb1217 commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SignInActivity.kt
> +                val userPwd: String = etPwd.text.toString()
그리고 아래 코드를 봤는데 toString()의 경우 빼주셔도 괜찮을 것 같아요!!

2021-10-19 16:10 UTC, mdb1217 commented on 29th_first_semina/build.gradle
> +        jcenter() // Warning: this repository is going to shut down soon
jcenter는 최근에 지원 중단 및 서비스 종료 되었습니다.(2022년 2월까지는 아티팩트를 제공하기는 하나, JCenter를 통한 업데이트는 더이상 이뤄지지않아요..😂) 그래서 이부분은 삭제해주시면 좋을 것 같아요 :)

2021-10-20 04:21 UTC, ssonghyun101 commented on 29th_first_semina/app/build.gradle
> +        minSdkVersion 28
엄,...어... 예전에 뭐 에러나길래 어쩌저찌하다가 28이 된거 같아요

2021-10-20 04:22 UTC, ssonghyun101 commented on 29th_first_semina/build.gradle
> +        jcenter() // Warning: this repository is going to shut down soon
앗 헐 넵

2021-10-20 04:45 UTC, merged