2차 세미나 필수과제
29th-WE-SOPT-Android-Part/Android-Songhyeon pull request #3
Opened 2021-10-21 19:46 UTC by ssonghyun101

2차 세미나 필수과제 완료오!

2021-10-22 03:21 UTC, l2hyunwoo requested changes
화이팅!

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/SampleActivity.kt
> +
빈칸 줄여주세요

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/ui/view/follwer/FollowerAdapter.kt
> +
빈칸 줄여주세요

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/ui/view/follwer/FollowerAdapter.kt
> +    override fun getItemCount(): Int = follwerList.size
```suggestion
    override fun getItemCount() = follwerList.size
```

코틀린에는 타입 자동추론기능이 있으니 적극 활용해보시는걸 추천드립니다

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/ui/view/follwer/FollowerAdapter.kt
> +    val follwerList = mutableListOf<FollowerData>()
이런 방식으로 작성한다면 다른 클래스(Fragment나 Activity)에서 FollwerAdapter의 프로퍼티에 접근하는 방식이 된다고 볼 수 있겠죠?

외부 클래스에서 내부의 상태를 조작하는 것은 지양되어야 하는 패턴 중 하나입니다. 가장 단순하게 이유를 들어보자면, 상태를 내부에서만 관리하게 된다면 상태와 관련된 Exception이 터질 경우 그 클래스 내부에서만 오류를 확인하면 되는데, 외부에 공개를 해버리면 해당 클래스뿐만 아니라 상태를 조작하는 다른 클래스들 모두를 확인해야겠죠? 

또한 멀티스레드 환경에서 가변 자료구조를 공개하는 경우 개발자가 예상하지 못하는 Side Effect가 있을 수 있습니다. 이 부분 잘 고려해보시고 수정하면 좋을 것 같습니다.

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/ui/view/follwer/FollowerFragment.kt
> +        val followerAdapter = FollowerAdapter()
굳! RecyclerView의 어댑터는 뷰에 종속되어 있는 상태 변수이기에 클래스 멤버변수로 둘 경우에는 nullable하게 둬야합니다. 하지만 이런 로컬변수로 두는 경우에는 함수 스택이 끝나면 자동으로 해제되기 때문에 안전하게 사용할 수 있겠죠

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/ui/view/follwer/FollowerFragment.kt
> +        followerAdapter.notifyDataSetChanged()
이 또한 외부에서 어댑터의 상태를 변경한다고 볼 수 있기때문에 지양되어야 하는 패턴으로 생각할 수 있습니다.

2021-10-22 03:21 UTC, l2hyunwoo commented on 29th_first_semina/app/src/main/java/com/example/a29th_first_semina/ui/view/repository/RepositoryFragment.kt
> +    }
binding은 View가 Destory하는 시점과 객체 해제 시점이 일치하지 않아 발생하는 것이기 때문에 onDestroyView에서 해제해야 합니다.

2021-10-26 16:08 UTC, mdb1217 approved these changes

2021-12-21 12:20 UTC, merged